"""Seed-vs-optimized comparison plots for the full pumping-cycle optimization.

Companion to ``run_full_cycle_opti.py``: after a successful staged solve it
renders a detailed comparison between the *initial guess* (the seed cycle
generated by ``fit_periodic_cycle_config.py`` and forward-simulated as the NLP
warm start) and the *optimized* cycle. Three figures are saved next to the
optimized YAML/CSV in the results directory:

  ``..._trajectory.png``   3D flight path and the azimuth-elevation wind
                           window (seed / optimized spline paths + the flown
                           node trajectories);
  ``..._timeseries.png``   states and controls over the cycle phase s --
                           radius, reel speed, tension, power, steering,
                           depower, angle of attack -- with the optimized
                           reel-in window shaded;
  ``..._power.png``        instantaneous + cycle-average power, cumulative
                           energy over the cycle, the winch operating plane
                           T(v_r) against the force law and clamps, and a
                           seed -> optimized metrics table.

The optimized series is read straight from the optimizer's own per-node
trajectory (``SimulationResult.optimized_trajectory``) -- no re-simulation is
needed: time is reconstructed from ``dt = ds / s_dot`` and the path angles
from the optimized spline at the solved (r, s) nodes. A re-simulated phase
can optionally be passed as ``optimized_phase`` to plot the re-flown cycle
instead.

All entry points are best-effort: a broken panel or missing variable costs
that trace only, never the run that produced the result.
"""

from pathlib import Path

import numpy as np

from awetrim.kinematics.parametrized_patterns import PeriodicBSpline

SEED_STYLE = {"color": "0.45", "linestyle": "--", "linewidth": 1.4}
OPT_STYLE = {"color": "tab:blue", "linestyle": "-", "linewidth": 1.7}
SEED_LABEL = "initial guess"
OPT_LABEL = "optimized"
REELIN_SHADE = {"color": "tab:orange", "alpha": 0.12, "zorder": 0}

_SERIES_KEYS = (
    "t",
    "s",
    "s_dot",
    "distance_radial",
    "speed_radial",
    "tension_tether_ground",
    "input_steering",
    "input_depower",
    "angle_azimuth",
    "angle_elevation",
    "speed_tangential",
    "mechanical_power",
    "angle_of_attack",
)


# ---------------------------------------------------------------------------
# Series extraction
# ---------------------------------------------------------------------------
def _ensure_power(series):
    if "mechanical_power" not in series and {
        "tension_tether_ground",
        "speed_radial",
    } <= series.keys():
        n = min(len(series["tension_tether_ground"]), len(series["speed_radial"]))
        series["mechanical_power"] = (
            series["tension_tether_ground"][:n] * series["speed_radial"][:n]
        )


def series_from_phase(phase):
    """Plain dict of numpy arrays from a simulated ``PhaseParameterized``.

    Variables the model does not expose (e.g. angle_of_attack on some
    configurations) are skipped; mechanical power falls back to T * v_r when
    not recorded.
    """
    out = {}
    for key in _SERIES_KEYS:
        try:
            values = np.asarray(phase.return_variable(key), dtype=float).ravel()
        except Exception:
            continue
        if values.size:
            out[key] = values
    _ensure_power(out)
    return out


def series_from_optimizer_result(result, path_parameters):
    """Series dict straight from the NLP solution (re-simulation fallback).

    ``optimized_trajectory`` carries the per-node decision values only, so
    time is integrated from ``dt = ds / s_dot`` and the path angles are
    evaluated from the optimized spline at the solved (r, s) nodes. Returns
    None when the result holds no trajectory.
    """
    traj = getattr(result, "optimized_trajectory", None) or {}
    if not traj:
        return None
    out = {k: np.asarray(v, dtype=float).ravel() for k, v in traj.items()}
    n = min(len(v) for v in out.values())
    out = {k: v[:n] for k, v in out.items()}
    _ensure_power(out)
    if "t" not in out and {"s", "s_dot"} <= out.keys():
        ds = np.diff(out["s"], prepend=out["s"][0])
        out["t"] = np.cumsum(ds / np.maximum(out["s_dot"], 1e-9))
    if (
        path_parameters is not None
        and "angle_azimuth" not in out
        and {"s", "distance_radial"} <= out.keys()
    ):
        try:
            pattern = _pattern(path_parameters)
            r, s = out["distance_radial"], out["s"]
            out["angle_azimuth"] = np.array(
                [float(pattern.azimuth(r[j], s[j])) for j in range(n)]
            )
            out["angle_elevation"] = np.array(
                [float(pattern.elevation(r[j], s[j])) for j in range(n)]
            )
        except Exception:
            pass
    return out


def _pattern(path_parameters):
    M = int(path_parameters["M"])
    return PeriodicBSpline(
        M=M,
        C_phi=np.asarray(path_parameters["C_phi"], dtype=float).reshape((M, 1)),
        C_beta=np.asarray(path_parameters["C_beta"], dtype=float).reshape((M, 1)),
        s_init=float(path_parameters.get("s_init", 0.0)),
        s_final=float(path_parameters.get("s_final", 1.0)),
        downloops=bool(path_parameters.get("downloops", True)),
    )


def _sample_spline(path_parameters, n_samples=600):
    """(azimuth, elevation) in degrees over one period of the config's spline."""
    pattern = _pattern(path_parameters)
    r0 = float(path_parameters["r0"])
    s = np.linspace(0.0, 1.0, n_samples, endpoint=True)
    phi = np.degrees([float(pattern.azimuth(r0, si)) for si in s])
    beta = np.degrees([float(pattern.elevation(r0, si)) for si in s])
    return phi, beta


# ---------------------------------------------------------------------------
# Metrics
# ---------------------------------------------------------------------------
def cycle_metrics(series):
    """Scalar cycle metrics (energy, power, closure, ...) from a series dict."""
    m = {}
    t = series.get("t")
    tension = series.get("tension_tether_ground")
    vr = series.get("speed_radial")
    if t is not None and tension is not None and vr is not None and len(t) > 1:
        n = min(len(t), len(tension), len(vr))
        t_n, tension_n, vr_n = t[:n], tension[:n], vr[:n]
        dt = np.diff(t_n, prepend=t_n[0])
        duration = float(t_n[-1] - t_n[0])
        m["energy"] = float(np.sum(tension_n * vr_n * dt))
        m["duration"] = duration
        m["avg_power"] = m["energy"] / max(duration, 1e-9)
        m["reelout_time_fraction"] = float(
            np.sum(dt[vr_n > 0.0]) / max(duration, 1e-9)
        )
        m["tension_mean"] = float(np.mean(tension_n))
        m["tension_max"] = float(np.max(tension_n))
    r = series.get("distance_radial")
    if r is not None and len(r) > 1:
        m["closure"] = float(r[-1] - r[0])
        m["r_min"], m["r_max"] = float(np.min(r)), float(np.max(r))
    u_s = series.get("input_steering")
    if u_s is not None and len(u_s):
        m["steer_absmax"] = float(np.max(np.abs(u_s)))
    dep = series.get("input_depower")
    if dep is not None and len(dep):
        m["depower_min"] = float(np.min(dep))
        m["depower_max"] = float(np.max(dep))
    return m


def _fmt(value, spec, unit=""):
    return "n/a" if value is None else f"{value:{spec}}{unit}"


def comparison_rows(seed_m, opt_m):
    """(metric, seed, optimized, change) rows for the console table and figure."""
    rows = []

    def add(name, key, spec, unit="", scale=1.0, pct=False):
        a, b = seed_m.get(key), opt_m.get(key)
        delta = ""
        if pct and a not in (None, 0) and b is not None:
            delta = f"{(b - a) / abs(a) * 100.0:+.1f}%"
        rows.append(
            (
                name,
                _fmt(None if a is None else a * scale, spec, unit),
                _fmt(None if b is None else b * scale, spec, unit),
                delta,
            )
        )

    def add_range(name, lo_key, hi_key, spec, unit=""):
        def _rng(m):
            lo, hi = m.get(lo_key), m.get(hi_key)
            if lo is None or hi is None:
                return "n/a"
            return f"{lo:{spec}}..{hi:{spec}}{unit}"

        rows.append((name, _rng(seed_m), _rng(opt_m), ""))

    add("average power", "avg_power", ".2f", " kW", scale=1e-3, pct=True)
    add("energy / cycle", "energy", ".2f", " MJ", scale=1e-6, pct=True)
    add("cycle duration", "duration", ".1f", " s")
    add("reel-out time fraction", "reelout_time_fraction", ".2f")
    add("closure r_end - r0", "closure", "+.2f", " m")
    add_range("radius range", "r_min", "r_max", ".1f", " m")
    add("tension mean", "tension_mean", ".2f", " kN", scale=1e-3)
    add("tension max", "tension_max", ".2f", " kN", scale=1e-3)
    add("max |steering|", "steer_absmax", ".2f")
    add_range("depower range", "depower_min", "depower_max", ".2f", " m")
    return rows


def print_comparison(rows):
    """Aligned seed -> optimized metrics table on the console."""
    header = f"{'metric':<24}{'seed':>16}{'optimized':>16}{'change':>10}"
    print("\n--- Cycle comparison (seed -> optimized) ---")
    print(header)
    print("-" * len(header))
    for name, a, b, d in rows:
        print(f"{name:<24}{a:>16}{b:>16}{d:>10}")


# ---------------------------------------------------------------------------
# Figure helpers
# ---------------------------------------------------------------------------
def _iter_series(seed, opt):
    if seed:
        yield seed, SEED_STYLE, SEED_LABEL
    if opt:
        yield opt, OPT_STYLE, OPT_LABEL


def _mask_ranges(x, mask):
    """Contiguous x-ranges where ``mask`` is True, as (lo, hi) tuples."""
    idx = np.flatnonzero(mask)
    if idx.size == 0:
        return []
    ranges = []
    start = prev = idx[0]
    for j in idx[1:]:
        if j == prev + 1:
            prev = j
            continue
        ranges.append((float(x[start]), float(x[prev])))
        start = prev = j
    ranges.append((float(x[start]), float(x[prev])))
    return ranges


def _reelin_ranges(series):
    """s-ranges where the cycle reels in (v_r < 0); used for shading."""
    if not series or not {"s", "speed_radial"} <= series.keys():
        return []
    n = min(len(series["s"]), len(series["speed_radial"]))
    return _mask_ranges(series["s"][:n], series["speed_radial"][:n] < 0.0)


def _shade(ax, ranges):
    for lo, hi in ranges:
        ax.axvspan(lo, hi, **REELIN_SHADE)


def _equal_aspect_3d(ax):
    lims = np.array([ax.get_xlim3d(), ax.get_ylim3d(), ax.get_zlim3d()])
    spans = lims[:, 1] - lims[:, 0]
    ax.set_box_aspect(np.maximum(spans, 1e-9))


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------
def plot_trajectory_comparison(seed, opt, seed_path=None, opt_path=None, title=None):
    """3D flight path (left) and azimuth-elevation wind window (right)."""
    import matplotlib.pyplot as plt

    fig = plt.figure(figsize=(13.5, 6))
    ax3d = fig.add_subplot(1, 2, 1, projection="3d")
    ax_win = fig.add_subplot(1, 2, 2)

    for series, style, label in _iter_series(seed, opt):
        if not {"angle_azimuth", "angle_elevation", "distance_radial"} <= series.keys():
            continue
        phi, beta, r = (
            series["angle_azimuth"],
            series["angle_elevation"],
            series["distance_radial"],
        )
        n = min(len(phi), len(beta), len(r))
        phi, beta, r = phi[:n], beta[:n], r[:n]
        x = r * np.cos(beta) * np.cos(phi)
        y = r * np.cos(beta) * np.sin(phi)
        z = r * np.sin(beta)
        ax3d.plot(x, y, z, label=label, **style)
        ax3d.scatter(x[:1], y[:1], z[:1], color=style["color"], s=25)
        ax_win.plot(
            np.degrees(phi),
            np.degrees(beta),
            ".",
            color=style["color"],
            ms=3,
            alpha=0.5,
            zorder=3,
        )
    ax3d.scatter([0], [0], [0], marker="s", color="tab:brown", label="ground station")
    ax3d.set_xlabel("x (m)")
    ax3d.set_ylabel("y (m)")
    ax3d.set_zlabel("z (m)")
    ax3d.legend(loc="upper left", fontsize=9)
    ax3d.set_title("flight path (dots mark the cycle start)")
    _equal_aspect_3d(ax3d)

    # Prescribed spline paths under the simulated dots, sampled fine.
    for path, style, label in (
        (seed_path, SEED_STYLE, f"{SEED_LABEL} spline"),
        (opt_path, OPT_STYLE, f"{OPT_LABEL} spline"),
    ):
        if path is None:
            continue
        try:
            phi_deg, beta_deg = _sample_spline(path)
        except Exception:
            continue
        ax_win.plot(phi_deg, beta_deg, label=label, zorder=2, **style)
    ax_win.set_xlabel(r"azimuth $\phi$ (deg)")
    ax_win.set_ylabel(r"elevation $\beta$ (deg)")
    ax_win.grid(True, alpha=0.4)
    ax_win.legend(loc="best", fontsize=9)
    ax_win.set_title("wind window: spline paths + trimmed nodes")

    if title:
        fig.suptitle(title)
    fig.tight_layout()
    return fig


def plot_timeseries_comparison(seed, opt, title=None):
    """Stacked state/control panels over the cycle phase s, seed vs optimized."""
    import matplotlib.pyplot as plt
    from matplotlib.patches import Patch

    panels = [
        ("distance_radial", "$r$ (m)", 1.0, False),
        ("speed_radial", "$v_r$ (m/s)", 1.0, False),
        ("tension_tether_ground", "$F_t$ (kN)", 1e-3, False),
        ("mechanical_power", "$P$ (kW)", 1e-3, False),
        ("input_steering", "$u_s$ (-)", 1.0, False),
        ("input_depower", "$l_{dp}$ (m)", 1.0, False),
        ("angle_of_attack", r"$\alpha$ (deg)", 1.0, True),
    ]
    panels = [
        p for p in panels if (seed and p[0] in seed) or (opt and p[0] in opt)
    ]
    if not panels:
        raise ValueError("no plottable variables in either series")

    fig, axes = plt.subplots(
        len(panels),
        1,
        sharex=True,
        figsize=(10, 1.7 * len(panels) + 0.8),
    )
    axes = np.atleast_1d(axes)

    reelin = _reelin_ranges(opt) or _reelin_ranges(seed)
    for ax, (key, ylabel, scale, to_deg) in zip(axes, panels):
        for series, style, label in _iter_series(seed, opt):
            if key not in series or "s" not in series:
                continue
            n = min(len(series["s"]), len(series[key]))
            y = series[key][:n]
            y = np.degrees(y) if to_deg else y * scale
            ax.plot(series["s"][:n], y, label=label, **style)
        _shade(ax, reelin)
        ax.set_ylabel(ylabel)
        ax.grid(True, alpha=0.4)

    handles, _ = axes[0].get_legend_handles_labels()
    if reelin:
        handles.append(
            Patch(
                color=REELIN_SHADE["color"],
                alpha=2 * REELIN_SHADE["alpha"],
                label="reel-in ($v_r < 0$)",
            )
        )
    axes[0].legend(handles=handles, loc="upper right", ncol=3, fontsize=9)
    axes[-1].set_xlabel("cycle phase $s$ (-)")
    if title:
        fig.suptitle(title)
    fig.tight_layout()
    return fig


def plot_power_summary(
    seed, opt, seed_m, opt_m, rows, seed_config=None, opt_config=None, title=None
):
    """Power, cumulative energy, winch operating plane and the metrics table."""
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(2, 2, figsize=(13, 8.5))
    ax_p, ax_e, ax_w, ax_t = axes.ravel()

    # Instantaneous power vs s, with cycle-average lines.
    reelin = _reelin_ranges(opt) or _reelin_ranges(seed)
    for (series, style, label), metrics in zip(
        _iter_series(seed, opt), (m for m in (seed_m, opt_m) if m is not None)
    ):
        if {"s", "mechanical_power"} <= series.keys():
            n = min(len(series["s"]), len(series["mechanical_power"]))
            ax_p.plot(
                series["s"][:n],
                series["mechanical_power"][:n] / 1e3,
                label=label,
                **style,
            )
        if metrics.get("avg_power") is not None:
            ax_p.axhline(
                metrics["avg_power"] / 1e3,
                color=style["color"],
                linestyle=":",
                linewidth=1.2,
                label=f"{label} avg ({metrics['avg_power'] / 1e3:.1f} kW)",
            )
    ax_p.axhline(0.0, color="k", linewidth=0.6)
    _shade(ax_p, reelin)
    ax_p.set_xlabel("cycle phase $s$ (-)")
    ax_p.set_ylabel("$P$ (kW)")
    ax_p.grid(True, alpha=0.4)
    ax_p.legend(loc="best", fontsize=8)
    ax_p.set_title("instantaneous and cycle-average power")

    # Cumulative energy over the cycle (each series on its own clock).
    for series, style, label in _iter_series(seed, opt):
        if not {"t", "tension_tether_ground", "speed_radial"} <= series.keys():
            continue
        n = min(
            len(series["t"]),
            len(series["tension_tether_ground"]),
            len(series["speed_radial"]),
        )
        t = series["t"][:n]
        dt = np.diff(t, prepend=t[0])
        energy = np.cumsum(
            series["tension_tether_ground"][:n] * series["speed_radial"][:n] * dt
        )
        ax_e.plot(t - t[0], energy / 1e6, label=label, **style)
    ax_e.axhline(0.0, color="k", linewidth=0.6)
    ax_e.set_xlabel("$t$ (s)")
    ax_e.set_ylabel("cumulative energy (MJ)")
    ax_e.grid(True, alpha=0.4)
    ax_e.legend(loc="best", fontsize=9)
    ax_e.set_title("energy harvested over the cycle")

    # Winch operating plane: every trimmed node in (v_r, F_t), against the
    # depower-shifted force law (drawn at the depower extremes) and the clamps.
    for series, style, label in _iter_series(seed, opt):
        if not {"speed_radial", "tension_tether_ground"} <= series.keys():
            continue
        n = min(len(series["speed_radial"]), len(series["tension_tether_ground"]))
        ax_w.scatter(
            series["speed_radial"][:n],
            series["tension_tether_ground"][:n] / 1e3,
            s=10,
            alpha=0.55,
            color=style["color"],
            label=label,
        )
    radial = (opt_config or seed_config or {}).get("radial_parameters", {})
    try:
        slope = float(radial["slope_winch_ro"])
        offset0 = float(radial["offset_winch_ro"])
        gain = float(radial["winch_offset_depower_gain"])
        ref = float(radial["winch_depower_ref"])
        tf_min = float(radial["min_tether_force"])
        tf_max = float(radial["max_tether_force"])
        dep_src = (opt or seed or {}).get("input_depower")
        dep_lo = float(np.min(dep_src)) if dep_src is not None else ref
        dep_hi = float(np.max(dep_src)) if dep_src is not None else ref
        vr_lo, vr_hi = ax_w.get_xlim()
        vr_line = np.linspace(vr_lo, vr_hi, 200)
        for l_dp, ls in ((dep_lo, "-"), (dep_hi, "--")):
            offset = offset0 + gain * (l_dp - ref)
            t_line = np.clip(slope * (vr_line - offset), tf_min, tf_max)
            ax_w.plot(
                vr_line,
                t_line / 1e3,
                color="tab:red",
                linestyle=ls,
                linewidth=1.1,
                label=f"winch law @ $l_{{dp}}$={l_dp:.2f} m",
            )
        for clamp in (tf_min, tf_max):
            ax_w.axhline(clamp / 1e3, color="0.7", linewidth=0.8, zorder=0)
    except (KeyError, TypeError, ValueError):
        pass  # non-force-law configs: the operating points alone still inform
    ax_w.set_xlabel("$v_r$ (m/s)")
    ax_w.set_ylabel("$F_t$ (kN)")
    ax_w.grid(True, alpha=0.4)
    ax_w.legend(loc="best", fontsize=8)
    ax_w.set_title("winch operating plane")

    # Metrics table.
    ax_t.axis("off")
    header = f"{'metric':<24}{'seed':>16}{'optimized':>16}{'change':>9}"
    lines = [header, "-" * len(header)]
    lines += [f"{name:<24}{a:>16}{b:>16}{d:>9}" for name, a, b, d in rows]
    ax_t.text(
        0.0,
        0.95,
        "\n".join(lines),
        family="monospace",
        fontsize=9,
        va="top",
        transform=ax_t.transAxes,
    )
    ax_t.set_title("cycle metrics")

    if title:
        fig.suptitle(title)
    fig.tight_layout()
    return fig


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
def save_cycle_comparison_plots(
    *,
    baseline_phase,
    optimized_phase=None,
    result=None,
    seed_config=None,
    optimized_config=None,
    out_dir=".",
    tag="cycle",
    show=False,
    dpi=150,
):
    """Build and save the seed-vs-optimized comparison figures.

    The optimized cycle comes straight from ``result`` (a
    ``SimulationResult``) -- the NLP's own per-node trajectory, no
    re-simulation involved. Passing ``optimized_phase`` (a re-simulated
    phase) overrides that source. Figures are written to ``out_dir`` and,
    unless ``show``, closed after saving (with ``show`` they stay open for
    the caller's ``plt.show()``). Returns the list of written paths.
    """
    import matplotlib.pyplot as plt

    seed = series_from_phase(baseline_phase) if baseline_phase is not None else None
    opt = None
    if optimized_phase is not None:
        opt = series_from_phase(optimized_phase)
        opt_source = "re-simulated optimized cycle"
    if not opt and result is not None:
        opt = series_from_optimizer_result(
            result, (optimized_config or {}).get("path_parameters")
        )
        opt_source = "NLP's own per-node solution"
    if opt:
        print(f"Comparison plots: optimized series from the {opt_source}.")
    else:
        print("Comparison plots: no optimized series available; plotting seed only.")

    seed_m = cycle_metrics(seed) if seed else {}
    opt_m = cycle_metrics(opt) if opt else {}
    rows = comparison_rows(seed_m, opt_m)
    print_comparison(rows)

    seed_path = (seed_config or {}).get("path_parameters")
    opt_path = (optimized_config or {}).get("path_parameters")
    figures = (
        (
            "trajectory",
            lambda: plot_trajectory_comparison(
                seed, opt, seed_path=seed_path, opt_path=opt_path, title=tag
            ),
        ),
        ("timeseries", lambda: plot_timeseries_comparison(seed, opt, title=tag)),
        (
            "power",
            lambda: plot_power_summary(
                seed,
                opt,
                seed_m,
                opt_m,
                rows,
                seed_config=seed_config,
                opt_config=optimized_config,
                title=tag,
            ),
        ),
    )

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    saved = []
    for name, builder in figures:
        try:
            fig = builder()
        except Exception as exc:
            print(f"(comparison figure '{name}' unavailable: {exc})")
            continue
        path = out_dir / f"full_cycle_compare_{tag}_{name}.png"
        fig.savefig(path, dpi=dpi, bbox_inches="tight")
        saved.append(path)
        if not show:
            plt.close(fig)
    if saved:
        print("Comparison plots saved to:")
        for path in saved:
            print(f"  {path}")
    return saved
